#ifndef _COMPAT_LINUX_MMAN_H
#define _COMPAT_LINUX_MMAN_H
#define MAP_SHARED 0x01
#define MAP_PRIVATE 0x02
#define MAP_SHARED_VALIDATE 0x03
#define MAP_FIXED 0x10
#define MAP_ANONYMOUS 0x20
#define MAP_GROWSDOWN 0x0100
#define MAP_DENYWRITE 0x0800
#define MAP_STACK 0x00020000
#define MAP_JIT 0x0800
#define MAP_HUGETLB 0x040000
#define MADV_NORMAL 0
#define MADV_RANDOM 1
#define MADV_SEQUENTIAL 2
#define MADV_WILLNEED 3
#define MADV_DONTNEED 4
#define MADV_FREE 8
#define MADV_REMOVE 9
#define MADV_DONTFORK 10
#define MADV_DOFORK 11
#define MADV_MERGEABLE 12
#define MADV_UNMERGEABLE 13
#define MADV_HUGEPAGE 14
#define MADV_NOHUGEPAGE 15
#define MCL_CURRENT 1
#define MCL_FUTURE 2
#define MREMAP_MAYMOVE 1
#define MREMAP_FIXED 2
#endif
