#ifndef _COMPAT_LINUX_UNISTD_H
#define _COMPAT_LINUX_UNISTD_H
#define __NR_restart_syscall 0
#define __NR_exit 1
#define __NR_fork 2
#define __NR_read 0
#define __NR_write 1
#define __NR_open 2
#define __NR_close 3
#define __NR_waitpid 7
#define __NR_creat 85
#define __NR_link 86
#define __NR_unlink 87
#define __NR_execve 59
#define __NR_chdir 12
#define __NR_fchdir 133
#define __NR_mknod 133
#define __NR_chmod 90
#define __NR_chown 92
#define __NR_lseek 8
#define __NR_mount 165
#define __NR_umount2 52
#define __NR_ptrace 101
#define __NR_sync 36
#define __NR_kill 37
#define __NR_rename 82
#define __NR_mkdir 83
#define __NR_rmdir 84
#define __NR_dup 41
#define __NR_pipe 42
#define __NR_times 201
#define __NR_brk 12
#define __NR_setuid 105
#define __NR_getuid 102
#define __NR_setgid 106
#define __NR_getgid 104
#define __NR_geteuid 107
#define __NR_getegid 108
#define __NR_setpgid 109
#define __NR_getppid 64
#define __NR_setsid 112
#define __NR_setreuid 126
#define __NR_setregid 127
#define __NR_getgroups 80
#define __NR_setgroups 81
#define __NR_setresuid 113
#define __NR_getresuid 114
#define __NR_setresgid 115
#define __NR_getresgid 116
#define __NR_getpgid 103
#define __NR_getpgrp 111
#define __NR_setfsuid 119
#define __NR_setfsgid 120
#define __NR_getsid 125
#define __NR_capget 125
#define __NR_capset 126
#define __NR_rt_sigaction 13
#define __NR_rt_sigprocmask 14
#define __NR_rt_sigpending 127
#define __NR_rt_sigtimedwait 128
#define __NR_rt_sigreturn 15
#define __NR_sgetmask 68
#define __NR_ssetmask 69
#define __NR_signal 67
#define __NR_acct 163
#define __NR_umount 52
#define __NR_swapon 87
#define __NR_swapoff 88
#define __NR_sysinfo 116
#define __NR_ipc 117
#define __NR_fsync 118
#define __NR_clone 56
#define __NR_fork 57
#define __NR_vfork 58
#define __NR_execve 59
#define __NR_exit_group 231
#define __NR_wait4 61
#define __NR_kill 62
#define __NR_setuname 170
#define __NR_mmap 9
#define __NR_mprotect 10
#define __NR_munmap 11
#define __NR_mremap 25
#define __NR_msync 26
#define __NR_madvise 28
#define __NR_shmget 29
#define __NR_shmat 30
#define __NR_shmctl 31
#define __NR_dup2 33
#define __NR_pause 34
#define __NR_nanosleep 35
#define __NR_getitimer 36
#define __NR_alarm 37
#define __NR_setitimer 38
#define __NR_getpid 39
#define __NR_sendfile 40
#define __NR_socket 41
#define __NR_connect 42
#define __NR_accept 43
#define __NR_sendto 44
#define __NR_recvfrom 45
#define __NR_sendmsg 46
#define __NR_recvmsg 47
#define __NR_shutdown 48
#define __NR_bind 49
#define __NR_listen 50
#define __NR_getsockname 51
#define __NR_getpeername 52
#define __NR_socketpair 53
#define __NR_setsockopt 54
#define __NR_getsockopt 55
#define __NR_clone 56
#define __NR_fork 57
#define __NR_vfork 58
#define __NR_rt_sigreturn 15
#define __NR_set_tls 158
#define __NR_clock_gettime 228
#define __NR_clock_getres 229
#define __NR_clock_nanosleep 230
#define __NR_gettid 186
#define __NR_tgkill 234
#define __NR_futex 202
#define __NR_set_robust_list 99
#define __NR_get_robust_list 100
#define __NR_epoll_create 213
#define __NR_epoll_wait 232
#define __NR_epoll_ctl 233
#define __NR_signalfd4 277
#define __NR_eventfd2 290
#define __NR_timerfd_create 283
#define __NR_timerfd_settime 286
#define __NR_timerfd_gettime 287
#define __NR_epoll_create1 291
#define __NR_signalfd 282
#define __NR_eventfd 284
#define __NR_inotify_init1 294
#define __NR_inotify_add_watch 254
#define __NR_inotify_rm_watch 255
#define __NR_openat 56
#define __NR_newfstatat 262
#define __NR_unlinkat 263
#define __NR_renameat2 302
#define __NR_mkdirat 258
#define __NR_faccessat 269
#define __NR_fchmodat 268
#define __NR_fchownat 260
#define __NR_openat2 437
#define __NR_prlimit64 302
#define __NR_getrandom 318
#define __NR_memfd_create 319
#define __NR_statx 332
#define __NR_rseq 334
#define __NR_sysinfo 116
#endif
